command_timeout = 1000
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false 

format = "➜ $directory $git_branch $git_state $git_status $character"


right_format = """$all"""

palette = "rose_pine"

[palettes.rose_pine]
rose = "#ebbcba"
foam = "#9ccfd8"
iris = "#c4a7e7"
gold = "#f6c177"
pine = "#31748f"
love = "#eb6f92"
highlight = "#ea9a97"
text = "#e0def4"
muted = "#6e6a86"
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = " "
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
style = "foam"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:iris"
format = " on [$symbol $branch]($style)"

[git_status]
style = "fg:highlight"
format = ' [($all_status$ahead_behind )]($style)'

[character]
success_symbol = '[❯](bold fg:foam)'
error_symbol = '[❯](bold fg:love)'
vimcmd_symbol = '[](bold fg:gold)'
vimcmd_replace_one_symbol = '[](bold fg:rose)'
vimcmd_replace_symbol = '[](bold fg:rose)'
vimcmd_visual_symbol = '[](bold fg:iris)'

[nodejs]
symbol = ""
format = '[ $symbol( $version) ](fg:foam)'

[c]
symbol = " "
format = '[[ $symbol( $version) ]]($style)'

[rust]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[golang]
symbol = ""
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[java]
symbol = " "
format = '[[ $symbol( $version) ]]($style)'

[kotlin]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[haskell]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[python]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[docker_context]
symbol = ""
format = '[ $symbol( $context) ]($style)'

[time]
disabled = true

[line_break]
disabled = true
